# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('cmz_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='header_image',
            field=models.ImageField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(), upload_to='blog-images'),
        ),
    ]
