# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmz_blog', '0003_auto_20160930_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposttranslation',
            name='intro',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
