# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmz_blog', '0006_blogpost_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date']},
        ),
    ]
