# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-28 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
            ],
            options={
                'managed': True,
                'abstract': False,
                'db_table': 'technologies_tech_translation',
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='tech',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tech',
            name='title',
        ),
        migrations.AddField(
            model_name='techtranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='technologies.Tech'),
        ),
        migrations.AlterUniqueTogether(
            name='techtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
