# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0002_auto_20160928_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
