# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0003_tech_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='technology-icons'),
        ),
    ]
