# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0004_auto_20160930_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='icon',
            field=models.ImageField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage, upload_to='technology-icons'),
        ),
    ]
