# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologies', '0005_auto_20160930_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='tech',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
