# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NamedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('upload', models.ImageField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(), upload_to='cmz-files')),
            ],
        ),
    ]
