# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-06 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('cmz_files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedfile',
            name='thumb',
            field=models.FileField(blank=True, editable=False, null=True, storage=django_s3_storage.storage.S3Storage(), upload_to='cmz-files'),
        ),
        migrations.AlterField(
            model_name='namedfile',
            name='upload',
            field=models.FileField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(), upload_to='cmz-files'),
        ),
    ]
