# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-30 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_s3_storage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_image', models.ImageField(blank=True, null=True, storage=django_s3_storage.storage.S3Storage(), upload_to='portfolio-images')),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('blue_tags', models.CharField(blank=True, max_length=200, null=True)),
                ('red_tags', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioItemTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intro', models.TextField(blank=True, max_length=1000, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('language_code', models.CharField(db_index=True, max_length=15)),
                ('master', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cmz_portfolio.PortfolioItem')),
            ],
            options={
                'managed': True,
                'abstract': False,
                'db_table': 'cmz_portfolio_portfolioitem_translation',
                'db_tablespace': '',
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='portfolioitemtranslation',
            unique_together=set([('language_code', 'master')]),
        ),
    ]
