# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmz_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='order',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
