# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmz_portfolio', '0002_auto_20161004_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
